### ISSUE TITLE
More than one city

### ISSUE THREAD

**Issue by sharma-ji** [mykle1/MMM-Events#10]
Can I parse more than one city using array?

**Comment by mykle1** [comment]
I never tried. You can certainly take a shot at it if you want to. A quick workaround might be having 2 instances of the module. You'd have to rename one of them (example MMM-Events2) and use another city in the second instance of the config. Thanks for your interest.

**Comment by mykle1** [comment]
Contact me in the forum. I only just saw this comment

**Comment by E3V3A** [comment]
Yeah, that would be nice...
