### ISSUE TITLE
How to choose several event types?

### ISSUE THREAD

**Issue by E3V3A** [mykle1/MMM-Events#11]
I'd like to choose more than one event type.   
Is that possible? How?

**Comment by E3V3A** [comment]
Hi @mykle1 
I tried this module but the events website sucks so bad that I'm not able to even find any events or report the bugs they have on their website... Too bad!

**Comment by mykle1** [comment]
Sooo, I can close the issue? lmfao! I did.
However, I just installed it and it fires right up on my machine and it has been running flawlessly on my Pi mirror since I wrote it. Are you choosing from the events list that is at the bottom of the readme file?

**Comment by thiagofneves** [comment]
For future references:
"music | food | art"

**Comment by jaredmichaelwilliams** [comment]
@E3V3A @thiagofneves 

i read through the eventful API, and tested it out on my own

you shouldnt use `'|'` to seperate, you should use commas

i.e  DO this: `eventType: "music_electronic,music_jazz,music_vocal,music_rap_hiphop,comedy,science"`

NOT this`eventType: "music_electronic|music_jazz|music_vocal|music_rap_hiphop|comedy|science"`

@mykle1 you should add to the README that people can add commas between event types so they can select more than one kind

**Comment by jaredmichaelwilliams** [comment]
@mykle1 thanks for updating the readme! 

i know anyone that wants to use more than one (like me) will appreciate it
