### ISSUE TITLE
Events not displalying

### ISSUE THREAD

**Issue by lrmansfi** [mykle1/MMM-Events#13]
Hi, I have loaded the Events module onto my magic mirror and obtained key from eventful link provided. I used the example provided for config.js for testing purposes (with exception of key obtained from eventful site) yet all that loads is "Upcoming Events..." not sure what else i could be missing.

**Comment by mykle1** [comment]
open a topic on the forum and post your config entry there. I'm not seeing this behavior nor has anyone reported such an issue.

**Comment by sankalp1857** [comment]
Hi,

I am facing the same issue as well. Please can you help on how to proceed further.

**Comment by mykle1** [comment]
I just loaded this and it works as expected. Post a topic on the MM forum including your config entry and I'll help you
