### ISSUE TITLE
Can you have as a list?

### ISSUE THREAD

**Issue by Yeremiy** [mykle1/MMM-Events#14]
Hi. Can you have as a list? Not as one by one. I want to see some games ahead at the same time. Thank you

**Comment by mykle1** [comment]
Yes, you can. It's in the readme. Can you find it? :-)

Or did you mean at the same time. Only one at a time but you can have multiple eventTypes

**Comment by Yeremiy** [comment]
Hey.  at the moment I see one game per screen that are changing.  I would like to see as a list, for example:
 Madrid Barcelona - day of the game - time - place of play
 Barcelona Zaragoza - tar games - time  - place of the game, 
etc.  
See en fron. thank

**Comment by mykle1** [comment]
Yes, that is the way that the module is designed. I don't have any plans to change the way it works. Feel free to fork the repo and make your modifications.

**Comment by Yeremiy** [comment]
It’s a pity, but I’m not a programmer, I can’t help with anything. thank
