### ISSUE TITLE
Picture noch changing

### ISSUE THREAD

**Issue by Abert2002** [mykle1/MMM-Events#15]
I love this module, there is only a part i don't understand: The picture is all the time the same. It doesn't mater what kind of event.

This is my config:
```
{
			module: 'MMM-Events',
			position: 'top_left',
				config: {
				city: "Hannover",	 // Your City
				eventType: "performing_arts,comedy",	// Choose from Events List below
				when: "Next week",                
				mode: "noFrame",    // "Frame" or "noFrame" (around picture)
				apikey: "112233",
				rotateInterval: 20000,     // New Event Appears every 3 minutes
				useHeader: true,	           // Set to true if you want a header
				header: "Veranstaltungen in Hannover",
				animationSpeed: 3000,              // Event fades in and out
				picture: true,                     // true, false = no image
						}
		},
```

![Day](https://user-images.githubusercontent.com/33970832/82095577-9773d880-96ff-11ea-9ba6-6b7e9ad0e346.jpg)

**Comment by mykle1** [comment]
If you are seeing only that image then the api is not providing pictures for that event. As a test, try using New York City and you will see that the pictures work correctly because they are present in the data.
