### ISSUE TITLE
Multiple event instances

### ISSUE THREAD

**Issue by johnpaularthur** [mykle1/MMM-Events#16]
I'm trying to display 3 of these at once, each with different search patterns.  What happens is that all three are updated with the same result (usually the first one to return).   Anyway to correct this?

**Comment by mykle1** [comment]
That's not really an issue. The module works as it was made. You could try copying the module folder 2 times and rename the copies. You would have to make changes to the files of the copies, changing all instances of MMM-Events to match the new names .
I have not tried this. If it does work you would have 3 instances of the modules on the display. Sorry about that.
