### ISSUE TITLE
MMM-Events : nothing to display on my Magic Mirror

### ISSUE THREAD

**Issue by ghost** [mykle1/MMM-Events#17]
Hello,
I just installed the MMM-Events module and no events are displayed on my MM it remains blocked with "upcoming Events":
[url=https://zupimages.net/viewer.php?id=20/36/rren.png][img]https://zupimages.net/up/20/36/rren.png[/img][/url]

I created an API key :
[url=https://zupimages.net/viewer.php?id=20/36/jw25.png][img]https://zupimages.net/up/20/36/jw25.png[/img][/url]

here is my config.js:
```
		{
				module: 'MMM-Events',
				position: 'top_left',
				config: {
				city: "Caen",	           // Your City
				eventType: "music,movies_film,art", // One or more, seperated by commas. Choose from Events List below
				when: "This Week",                 // "All", "Future", "Past", "Today", "Last Week", "This Week", "Next week", and months by name, e.g. "October"
				mode: "noFrame",                   // "Frame" or "noFrame" (around picture)
				apikey: "Pq4n9Vh5zbshSVfS",
				rotateInterval: 5 * 60 * 1000,     // New Event Appears every 5 minutes
				useHeader: true,	           // Set to true if you want a header
				header: "Spectacle a proximité",
				animationSpeed: 3000,              // Event fades in and out
				picture: true,                     // true, false = no image
				}
			},
```
after typing the commands ```pm2 restart mm``` a reboot of my raspberry and created a new API Key always nothing...

Can you help me ?

**Comment by ghost** [comment]
https://zupimages.net/viewer.php?id=20/36/rren.png
https://zupimages.net/up/20/36/rren.png
https://zupimages.net/up/20/36/jw25.png
https://zupimages.net/viewer.php?id=20/36/jw25.png

**Comment by ghost** [comment]
by changing the city "Caen" (I live in Caen in Normandy) for "Paris", it works, it is therefore my city which is not recognized.
Any idea to solve the problem ?

https://zupimages.net/viewer.php?id=20/36/952n.png
https://zupimages.net/up/20/36/952n.png

**Comment by mykle1** [comment]
I've updated the module. Do a 'git pull' in the MMM-Events directory.
