### ISSUE TITLE
Unable to Obtain Eventful API Key

### ISSUE THREAD

**Issue by Dresch360** [mykle1/MMM-Events#18]
Hi there - I really like your Events module.
The link below is redirecting to https://www.radio.com/eventful when trying to create an API key under "Register a new account". 
Get FREE API key --> http://eventful.com/join?goto=http%3A%2F%2Fapi.eventful.com%2Fkeys#/ 

Any help would be greatly appreciated!

**Comment by mykle1** [comment]
This should do it

https://api.eventful.com/keys/new

I'll fix the readme. Thanks for bringing that to my attention

**Comment by Dresch360** [comment]
Sorry if I wasn't clear - When trying to create an API key from https://api.eventful.com/keys/new, under the "Register a new account" link, is redirecting to https://www.radio.com/eventful

**Comment by mykle1** [comment]
I understood. I gave you the new link to get your api key to use with MMM-Events. I also updated the readme to reflect the new link. That's where I thanked you for bringing it to my attention.

Or, am I missing something?
