### ISSUE TITLE
Eventful API link no longer working

### ISSUE THREAD

**Issue by BillieRubin** [mykle1/MMM-Events#19]
I have been using this for a few months and realized that it now just shows Upcoming Events.....  I thought that maybe the API key was expired and went to here:  https://api.eventful.com/keys/new   I see that the site no longer resolves.  Did they stop giving out free API keys.

**Comment by mykle1** [comment]
Yes, mine is doing the same thing. I'm trying to find out what happen to the api. As you noticed, there is no response. I tried to console log the response from the GET request in the module but there is no return there either, as if the api has been turned off or shut down. It doesn't look good. I'll see if there is another api that does the same thing but I am doubtful.
